FROM mcr.microsoft.com/mssql/server:2017-latest-ubuntu

RUN mkdir -p /docker-entrypoint-initdb.d

COPY ./docker-entrypoint-initdb.d/001_script.sql /docker-entrypoint-initdb.d/

CMD /opt/mssql/bin/sqlservr & sleep 20s && /opt/mssql-tools/bin/sqlcmd -S discoverhscountry-sql,1433 -U sa -P QWElkj132! -d master -i /docker-entrypoint-initdb.d/001_script.sql